[tox]
envlist =
    py{39,310,311,312,313}-test
isolated_build = true

[testenv]
# Run in a temporary directory to make sure we test the installed package
# rather than the local source tree (the repository and the package share the
# name "batchpr").
changedir = {envtmpdir}
extras = test
commands =
    pip freeze
    pytest --pyargs batchpr {posargs}
